language: python
dist: xenial
python: "3.7"
services: mysql
# env: DJANGO_VERSION=2.1.2
before_install: 
  - pip install pipenv
  - cd project
install: 
  - pip install -q Django===2.1.2
  - pip install pipfile
script: python manage.py test