language: python
dist: xenial
python: "3.7"
services: mysql
env: DJANGO=2.1.2 DB=mysql
before_install: 
  - pip install pipenv
install: 
  - pipenv run pip install pip==18.0 
  - pipenv install --dev --deploy
  - cd project
script: 
  - python manage.py test