language: python
sudo: required
dist: xenial
virtualenv: system_site_packages: true
python: "3.7"
services: mysql
# env: DJANGO_VERSION=2.1.2
install:
  - pip install pipfile
  - pip install -q Django==2.1.2
script: python manage.py test