<<<<<<< HEAD
# Generated by Django 2.1.1 on 2018-10-12 05:05
=======
# Generated by Django 2.1.1 on 2018-10-10 22:39
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
=======
                ('event_name', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=100)),
>>>>>>> master
                ('event_date', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=300)),
                ('l_name', models.CharField(max_length=300)),
<<<<<<< HEAD
                ('email', models.EmailField(max_length=254)),
=======
                ('email', models.EmailField(max_length=200)),
>>>>>>> master
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
