# Generated by Django 2.1.2 on 2018-10-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_venue', models.CharField(max_length=500)),
                ('event_city', models.CharField(max_length=400)),
                ('event_date', models.DateTimeField()),
                ('tickets_avail', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tic_type',
            field=models.CharField(choices=[('GA', 'General Admission'), ('VIP', 'VIP Seating'), ('AS', 'Assigned Seating')], default='GA', max_length=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.FloatField(default=0.0, max_length=25),
            preserve_default=False,
        ),
    ]
