# Generated by Django 2.1.2 on 2018-11-01 02:56

from django.db import migrations
import etes.managers


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('objects', etes.managers.TicketManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_avail',
        ),
    ]
