# Generated by Django 2.1.2 on 2018-11-01 02:58

from django.db import migrations
import etes.managers


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0002_auto_20181031_1956'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', etes.managers.EventManager()),
            ],
        ),
    ]
