# Generated by Django 2.1.2 on 2018-10-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0002_auto_20181016_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_event',
            field=models.CharField(default='anywhere', max_length=200),
            preserve_default=False,
        ),
    ]
