# Generated by Django 2.1.3 on 2018-11-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
