# Generated by Django 2.1.3 on 2018-11-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0007_auto_20181107_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
