# Generated by Django 2.1.3 on 2018-11-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0008_auto_20181107_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
