# Generated by Django 2.1.3 on 2018-11-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0009_remove_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
