# Generated by Django 2.1.3 on 2018-11-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0010_auto_20181107_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
    ]
