# Generated by Django 2.1.3 on 2018-11-14 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0011_auto_20181113_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 17, 3, 10, 88190)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
