# Generated by Django 2.1.3 on 2018-11-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0012_auto_20181114_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
