# Generated by Django 2.1.3 on 2018-11-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0013_auto_20181114_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
