# Generated by Django 2.1.3 on 2018-11-16 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0014_auto_20181114_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
