# Generated by Django 2.1.3 on 2018-11-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0015_auto_20181115_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
