# Generated by Django 2.1.3 on 2018-11-16 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0016_auto_20181115_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
