# Generated by Django 2.1.3 on 2018-11-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0017_auto_20181115_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
    ]
