# Generated by Django 2.1.3 on 2018-11-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0020_remove_ticket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(max_length=300),
        ),
    ]
