# Generated by Django 2.1.3 on 2018-11-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0021_auto_20181118_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
