# Generated by Django 2.1.3 on 2018-11-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0022_ticket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='quantity',
            new_name='ticket_quantity',
        ),
    ]
