# Generated by Django 2.1.3 on 2018-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0023_auto_20181119_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_address',
            field=models.CharField(default='San José State University, Washington Sq, San Jose, CA, United States', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
