# Generated by Django 2.1.3 on 2018-12-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etes', '0024_auto_20181119_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_fee',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_subtotal',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
    ]
